### PR TITLE
add a module to package.json

### PR DESCRIPTION
**Pull request by AWinterman**
this should let @pika/web include this module in it's dependency tree.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Thanks for the PR! Though, the `"module"` key is for ES modules, not CommonJS modules. I haven't used pika web, but they should have some way of loading CommonJS modules as well, right? Else it would be incompatible with the vast majority of npm packages out there that do not supply an ES modules version…

**Comment by AWinterman** [comment]
@goto-bus-stop that is exactly the issue-- they do not. I opened an issue against their repository: https://github.com/pikapkg/web/issues/44, but to no real avail.

**Comment by goto-bus-stop** [comment]
That issue suggests that it should work with `"webDependencies": ["events"]`, or am i wrong?

**Comment by AWinterman** [comment]
I don't really work on node, so I'm just going to close this pr. Someone else can pick it up if they want.

**Pull request closed without merging**
